import type { Metadata } from "next";
import "../styles/globals.css";

// components
import SideBar from "@/components/ui/sideBar/SideBar";
import ThemeProvider from "@/components/shared/ThemeProvider";
import ModalRenderer from "@/components/ui/modals/ModalRenderer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-gray-100 dark:bg-gray-900">
        <ThemeProvider>
          <div className="flex">
            <SideBar />
            {children}
          </div>
        </ThemeProvider>
        <ModalRenderer />
      </body>

      <script
        dangerouslySetInnerHTML={{
          __html: `
      (function() {
        const theme = localStorage.getItem('theme-storage');
        const preferredTheme = theme ? JSON.parse(theme).state.theme : 'light';
        document.documentElement.classList.add(preferredTheme);
      })();
    `,
        }}
      />
    </html>
  );
}
